
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: Deploy-kube-manifests
  value: kube  

stages:
  - stage: Deploy
    displayName: Deploy stage
    jobs:
      - job: Deploy-kube-manifests
        steps:

